version: "3.9"  

services:
    srvprueba: 
        image: georgeosantiago/whoami
        #image: nginx
        hostname: srvprueba
        domainname: srvprueba
        container_name: srvprueba
#        user: "root"
#        cap_add:
#            - NET_ADMIN        

        network_mode: bridge
        ports:
          - "80:80"

        
        
      
